# Site settings
title: M Shafique Qadri
twitter_username: mrshafiqueqadri
name: M Shafique Qadri

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/mrshafiqueqadri
 - title: StackOverflow
   url: https://stackoverflow.com/users/6144741/m-shafique-qadri
 - title: LinkedIn
   url: https://www.linkedin.com/in/m-shafique-qadri-62a69a96/

#Any buzzword skills you want to include
skills:
 - Angular
 - React-native
 - IONIC
 - Laravel
 - SQL
 - REST

#Blogfeed is optional - including this will add JS to call the feed and populate blog list

#Work experience is required
roles:
 - title: Software Engineer
   start: June 2017
   end: Present
   employer: Barefoot Studio
   description: Working as Laravel, NodeJS, React-native, Ionic and Angularjs Developer. 
 - title: Software Engineer
   start: August 2016
   end: May 2017
   employer: OSO
   description: Worked as Laravel, Ionic and Angularjs Developer.
 - title: Software Engineer
   start: August 2015
   end: August 2016
   employer: Mavenup
   description: Worked as Codeigniter and Angularjs Developer.

#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 2015
   subject: Information Technology
   school: University of Education, Pakistan

#List of interesting Github repo/projects to include - optional
github:
 - mrshafiqueqadri/Phpgmaps
 - mrshafiqueqadri/react-native-maps
 - mrshafiqueqadri/react-modules

#Stackoverflow flair is optional
stackoverflow:
   profileurl: hhttps://stackoverflow.com/users/6144741/m-shafique-qadri
   flairimageurl: https://i.stack.imgur.com/k5la5.jpg?s=48&g=1

#Mobile apps section is optional
apps:
 - name: KOWO
   platform: Android and IOS
   AndroidUrl: https://play.google.com/store/apps/details?id=be.barefoot.kowo.store
   IosUrl: https://play.google.com/store/apps/details?id=be.barefoot.kowo.store
   description: Developed on React-native and NODEJS.
 - name: Pets2Vet
   platform: Android and IOS
   AndroidUrl: https://play.google.com/store/apps/details?id=com.oso.petvet
   IosUrl: https://itunes.apple.com/gr/app/pets2vet/id1216091778?mt=8
   description: Developed on IONIC and LARAVEL.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   I kicked started my career working with MAVENUP in a well challenged and highly competitive environment, learning new and diverse technologies like CODEIGNITER, ANGULAR in one year's tenure.
   <br>After having decent enough flavor of the Industry i started working with OSO and specialized in LARAVEL, ANGULAR and IONIC frameworks in 10 Months time period.
   <br>Its been 8th Months or so that i've became part of this wonderful Company namely known as BAREFOOT STUDIO and putting my skills to best use in EXPRESSJS, ANGULAR, REACT-NATIVE, IONIC frameworks.
